---
- hosts: soa
  connection: ssh
  remote_user: "{{ oracle_user }}"
  #become: true
  gather_facts: no 
  vars_files:
  - group-vars/linux-wls-vars.yml
  - group-vars/infra-vars.yml
  - group-vars/secrets.yml
  roles:
  - role: linux-wls
    become: true
    become_user: root
    become_method: sudo
    tags: linux

  - role: linux-jdk-rpm
    become: true
    become_user: root
    become_method: sudo 
    tags: jdk

  - role: fmw-infra
    tags: infra

  - role: soa-install
    tags: soa-install
  
  - role: aia-install
    tags: aia-install

  - role: rcu
    tags: rcu
    run_once: true

  - role: soa-domain
    when: admin == "true"
    tags: admin    
  
  - role: soa-managed
    when: admin == "false"
    tags: managed
