- set_fact:
    components_list: null

- name: Prepare components list
  set_fact:
    components_list: "{{ components_list }}-component {{ item }} "
  with_items: 
  - "{{ schema_list }}"
  when: 
  - 'item != "UCSCC"' 
  - 'item != "UMS"'

- name: Copy passwords file
  template: 
    src: rcu.passwd.txt 
    dest: '{{ mw_installer_folder }}/'

- name: Run rcu to drop schemas
  shell: '{{ middleware_home }}/oracle_common/bin/rcu -silent -dropRepository -connectString {{ dbserver_name }}:{{ dbserver_port }}/{{ dbserver_service }} -dbUser {{ db_user }} -dbRole {{ db_role }} -schemaPrefix {{ soa_repo_preffix }} {{ components_list }}-f < {{ mw_installer_folder }}/rcu.passwd.txt'
  ignore_errors: yes

- name: Run rcu to create schemas
  shell: '{{ middleware_home }}/oracle_common/bin/rcu -silent -createRepository -connectString {{ dbserver_name }}:{{ dbserver_port }}/{{ dbserver_service }} -dbUser {{ db_user }} -dbRole {{ db_role }} -honorOMF -useSamePasswordForAllSchemaUsers true -variables -schemaPrefix {{ soa_repo_preffix }} {{ components_list }}-f < {{ mw_installer_folder }}/rcu.passwd.txt'
  #ignore_errors: yes
