- name: 'Java version {{ flag }} rpm installation'
  shell: command -v java && java -version
  register: jversion
  ignore_errors: true

- debug: var='{{ item }}'
  with_items:
  - jversion.stdout
  - jversion.stderr

