- name: Install required libraries
  yum: name={{ item }} state=present
  with_items: "{{ packages_list }}"
  
- name: Disable SELinux
  selinux: state=disabled
  
#- name: Disable Firewall Deamon (firewalld)
#  service: name=firewalld state=stopped enabled=no
  
- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: "{{ kernel_params }}"

- name: Create a shell profile with file and process limits for oracle user
  template: src=oracle-limits.sh dest=/etc/profile.d/

- name: Add oracle user limits
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} {{ item.limit }} {{ item.type}} {{ item.value }}'
  with_items:
    - { limit: 'soft', type: nofile, value: '{{ soft_no_file }}' }
    - { limit: 'hard', type: nofile, value: '{{ hard_no_file }}' }
    - { limit: 'soft', type: nproc, value: '{{ soft_nproc }}' }
    - { limit: 'hard', type: nproc, value: '{{ hard_nproc }}' }

- name: Create Oracle Home directory
  file: state=directory path={{ middleware_home }} owner={{ oracle_user }} group={{ oracle_group }}
  
- name: Create Domain Home directory
  file: state=directory path={{ domains_home }} owner={{ oracle_user }} group={{ oracle_group }}
  
- name: Create Applications Home directory
  file: state=directory path={{ applications_home }} owner={{ oracle_user }} group={{ oracle_group }}
