- name: check if domain folder exists
  stat: 
    path: '{{ domains_home }}/{{ domain_name }}'
  register: domain_exists

- name: copy create domain python script
  template: 
    src: create-domain.py 
    dest: '{{ mw_installer_folder }}'
    owner: '{{ oracle_user }}' 
    group: '{{ oracle_group }}'
  tags: template
  
- name: Execute create domain script
  shell: "{{ weblogic_home }}/common/bin/wlst.sh {{ mw_installer_folder }}/create-domain.py"
  when: domain_exists.stat.exists == False

- name: Add Oracle Home environment variables
  lineinfile: 
    dest: '/home/{{ oracle_user }}/.bashrc' 
    line: 'export ORACLE_HOME={{ middleware_home }}'
