- include: admin.yml
  when: admin == "true"

- include: managed.yml
  when: admin == "false"

#- name: Copy nmEnroll script
#  template: 
#    src: nmEnroll.py
#    dest: '{{ remote_jdk_path }}'

#- name: Enroll nodemanager
#  shell: '{{ middleware_home }}/oracle_common/common/bin/wlst.sh {{ remote_jdk_path }}/nmEnroll.py'

#- name: Stop Admin server
#  shell: 'cd {{ domains_home }}/{{ domain_name }}/bin && sh stopWebLogic.sh'
#  when: admin == "true"  
